### ISSUE TITLE
Install issue keystone https self-signed certificate

### ISSUE THREAD

**Issue by jarbis31** [ComputingStack/Uniview-OpenStack-Portal#1]
Hi,

I tried to install uniview with docker-compose. When container starts, i do not have any error but the container is in "unhealthy" state.
I configured docker-compose.yml file with needed variables. My particularity: my keystone URL api is in https protocol with a self-signed certificate.
Is it a way to configure uniview for this kind of configuration ?

Here is my configuration :
```
root@uniview-portal:/opt/app/docker-uniview# cat docker-compose.yml 
version: '3'
services:
  uniview1:
    image: computingstack/uniview-openstack-frontends:latest
    ports:
    - "3006:3006"
    healthcheck:
      test: curl --fail http://192.168.1.70:3006/getVersion || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
            #REGISTRY_AUTH: htpasswd
            #REGISTRY_AUTH_HTPASSWD_REALM: Registry
            #REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
            #REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      db_host: 192.168.1.70
      db_user: uniview
      db_password: Uniview01
      db_database: uniview
      keystone_auth_url: "https://keystone.gd1.cloud:5000"
      os_interface_type: public
      os_auth_user: admin
      os_auth_pass: xxxxxx
      os_auth_project: admin
      #uniview_key: xxxxx
      #ceph_api_url: http://1.2.3.4:8090
      #ceph_api_user: computingstack
      #ceph_api_pass: your_pass
      concurrent_sessions: 6
      log_level: debug
      #prometheus_url: http://1.2.3.4:9090
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        #max_attempts: 3
        window: 120s
    restart: always
```

Thanks for any help !

Best regards,

Mickaël Batailler
